# Generated by Django 6.0 on 2025-12-19 13:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان کلی دوره (مثلا پایتون مقدماتی)')),
                ('description', models.TextField(verbose_name='توضیحات پیش\u200cفرض')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.PositiveIntegerField(verbose_name='شماره دوره (مثلا 137)')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='نام کامل دوره')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active_for_signup', models.BooleanField(default=True, verbose_name='قابل انتخاب در ثبت\u200cنام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('students', models.ManyToManyField(blank=True, related_name='courses_joined', to=settings.AUTH_USER_MODEL, verbose_name='دانشجویان')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.coursetemplate', verbose_name='نوع دوره')),
            ],
            options={
                'unique_together': {('template', 'course_number')},
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('problem_statement', models.TextField()),
                ('is_locked', models.BooleanField(default=True, verbose_name='قفل است؟')),
                ('order', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='courses.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان تمرین')),
                ('problem_statement', models.TextField(verbose_name='صورت سوال')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='شماره ترتیب')),
                ('course_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_templates', to='courses.coursetemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_file', models.FileField(upload_to='submissions/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('teacher_comment', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.exercise')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
