# Generated by Django 6.0 on 2025-12-19 15:18

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_enrollmentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submitted_file',
            field=models.FileField(upload_to=courses.models.submission_file_path, verbose_name='فایل تمرین'),
        ),
    ]
