# Generated by Django 5.2 on 2025-12-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_submission_submitted_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='آکادمی پایتون', max_length=200, verbose_name='نام سایت')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='آیکون مرورگر (Favicon)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='لوگوی سایت (منو)')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
