# Generated by Django 5.2 on 2025-12-20 21:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_submission_feedback_alter_submission_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='teacher_comment',
        ),
        migrations.AlterField(
            model_name='course',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='active_courses', to='courses.coursetemplate', verbose_name='نوع دوره'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='بازخورد استاد'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نمره'),
        ),
    ]
