"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'default-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'django.contrib.sites',
    
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    
    'users.apps.UsersConfig',
    'courses.apps.CoursesConfig',
    
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(default='sqlite:///db.sqlite3')
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


AUTH_USER_MODEL = 'users.CustomUser'



MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'



# --- تنظیمات احراز هویت و ایمیل ---
SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# تنظیمات ارسال ایمیل (چاپ در ترمینال برای تست)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# تنظیمات رفتاری Allauth
ACCOUNT_AUTHENTICATION_METHOD = 'email' # ورود فقط با ایمیل
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False # یوزرنیم اجباری نیست (خودمان میسازیم)

# مهم: تایید ایمیل اجباری است
ACCOUNT_EMAIL_VERIFICATION = 'mandatory' 


ACCOUNT_FORMS = {'signup': 'users.forms.CustomSignupForm'}


# تنظیمات ایمیل و لینک‌ها
ACCOUNT_EMAIL_SUBJECT_PREFIX = "[آکادمی پایتون] "  # پیشوند ایمیل‌ها
ACCOUNT_CONFIRM_EMAIL_ON_GET = True

# اجازه خروج با درخواست GET (بدون تأییدیه)
ACCOUNT_LOGOUT_ON_GET = True

# بعد از خروج به صفحه اصلی سایت (لیست دوره‌ها) برو
LOGIN_REDIRECT_URL = 'courses:course_list'
LOGOUT_REDIRECT_URL = 'account_login'


STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
AWS_S3_ENDPOINT_URL = os.getenv('LIARA_ENDPOINT_URL')


if not DEBUG: # یعنی فقط روی سرور اینجوری باشد
    AWS_ACCESS_KEY_ID = os.getenv('LIARA_ACCESS_KEY')
    AWS_SECRET_ACCESS_KEY = os.getenv('LIARA_SECRET_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('LIARA_BUCKET_NAME')
    AWS_S3_ENDPOINT_URL = os.getenv('LIARA_ENDPOINT_URL')
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }
    AWS_LOCATION = 'media'
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    # MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.{os.getenv("LIARA_ENDPOINT_URL").split("://")[1]}/{AWS_LOCATION}/'
    if AWS_S3_ENDPOINT_URL:
    # حذف https:// از ابتدای آدرس برای ساختن لینک دانلود
        endpoint_clean = AWS_S3_ENDPOINT_URL.replace("https://", "").replace("http://", "")
        MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.{endpoint_clean}/{AWS_LOCATION}/'
    else:
        MEDIA_URL = '/media/' # جهت جلوگیری از کرش کردن در صورت نبودن متغیر
        
else:
    # روی لوکال همان روش قبلی
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
    

if not DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
    DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
else:
    # روی لوکال فقط چاپ کن
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# پیشوند عنوان ایمیل‌ها
ACCOUNT_EMAIL_SUBJECT_PREFIX = "[آکادمی پایتون] "
